[project]
name = "hopon-backend"
version = "0.1.0"
description = "HopOn Flask backend managed by uv"
requires-python = ">=3.10"
dependencies = [
  "Flask==3.0.3",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
